### PR TITLE
Allow parametric encoder via --encoder

### PR DESCRIPTION
**Pull request by SamuelePilleri**
This is useful for `h264_nvenc` encoders and such.

Couldn't test it since I have problems with libcairo on Windows, please test before merging.

### CODE REVIEW

**Comment by SamuelePilleri** [comment]
Ok, I managed to test with NVENC and it actually works great, went from a 5x to a solid 12x!

I also fixed a bug with files not being found in the concat phase.

I must note however that the output video doesn't play correctly on Windows and audio is muted. It plays correctly on third party software like Media Player Classic Home Cinema or VLC, but anyway I believe this is a bug and should be fixed.

**Comment by SamuelePilleri** [comment]
By the way, commit 8b000f7 fixes #5

**Comment by federicotorrielli** [comment]
Tested on Linux, it's good to go! --encoder nvenc on Arch (1660ti) brings 25x, not bad :)

**Comment by C0D3D3V** [comment]
Thank you very much for your PR :) I will merge it later. 



I think it does not play in windows media player or similar, because the player is missing the codec. Thats normal, these old playes doesn't support complex mixed up codecs as we use them.  Btw. I recomend mpv player :D

**Comment by SamuelePilleri** [comment]
Perhaps I should add my name to the authors list and write some documentation about the new flag. Please feel free to go for it, I will be away this weekend and probably won't have much time to look at it.

**Comment by C0D3D3V** [comment]
That's no problem, I'll take care of the rest. That's the least I can add to such a great contribution :)

**Pull request merged**
